### ISSUE TITLE
Edit Notes

### ISSUE THREAD

**Issue by Kaakyire9** [alice173/JS-exercises#5]
**User Story:** 
AS A user, I WANT TO edit an existing note SO THAT I CAN update or correct the information.

**Acceptance Criteria:**

- [ ] The user can click an "Edit" button next to a note.
- [ ] The note's text becomes editable.
- [ ] The user can save the changes.
- [ ] The updated note is displayed in the list of notes.

**Tasks:**

- [ ] Add an "Edit" button next to each note.
- [ ] Implement functionality to make the note text editable.
- [ ] Implement functionality to save the edited note.
- [ ] Update the list of notes to display the edited
